# Data Preprocessing Steps--

1)Importing the libraries

2)Importing the dataset

3)Taking Care of Missing Data 

4)Encoding categorical data--1) Encoding the Independent Variable  2) Encoding the Dependent Variable

                             
5)Splitting the dataset into the Training set and Test set

6)Feature Scaling

          



# Importing Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# importing Datsets

In [2]:
dataset=pd.read_csv('Data.csv')
X=dataset.iloc[:,:-1].values
Y=dataset.iloc[:, -1].values

In [3]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [4]:
Y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

# Taking Care of Missing Data 

In [5]:
from sklearn.impute import SimpleImputer              # Class Simple imputer taking from  Sklearn Impute Module 
imputer=SimpleImputer(missing_values=np.nan, strategy='mean')   #Creating instance of Class to feed imput or action they have to do
imputer.fit(X[:,1:3])
X[:, 1:3]=imputer.transform(X[:, 1:3])


In [6]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

# Encoding Categorical Data 

## for Encoding Independent Vairable----One Hot Encoding And Column Transformer class of compose and preprocessing module of sklearn library is Require---Then Create Object of class , use Fit_transform to replace the categorical values by numerical one

## class ct have  parameter  transformers & remainder

## transformers---take tuple of input---Encoding,Technique of encoding, and 3rd is index of independent categorical column 

## remainder--passthrough means remaining independent column will pass as it is 

## we are creating array for Further use


In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])], remainder='passthrough')  
X = np.array(ct.fit_transform(X))

In [8]:
X

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [9]:
## for Encoding dependent Vairable--Label Encoding Technique is used , then do fit_transform
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
Y=le.fit_transform(Y)

In [10]:
Y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

# Splitting Dataset Into Training Set And Test Set

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test=train_test_split(X,Y,test_size=0.2,random_state=1)

In [12]:
X_train

array([[0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 35.0, 58000.0]], dtype=object)

In [13]:
X_test

array([[0.0, 1.0, 0.0, 30.0, 54000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [14]:
Y_train

array([0, 1, 0, 0, 1, 1, 0, 1])

In [15]:
Y_test

array([0, 1])

# Feature Scaling

---> Feature Scaling is the tool allow to scale each and every feature so that our algorithem can't dominate one Feature on          another.

---> It will convert all features to same scale/level, we don't have to apply feature scaling to all algorithem of ML.
     Ex-Mulinomial Linear regression , as scaling factor is already presesnt for each feature(X)


Q. When Should Apply Feature scaling step in data preprocessing? after or before spliting the dataset?
   
Ans--   feature Scaling step shoulld be done after spliting dataset,as we want to test our model on unknown/new data to know           how much accurate our model is!

Two Main Technique of feature Scaling Are--

1.Standardisation

2.Normalization

*Standardisation--> We can use standardisation in all cases, Hence we prefer to do standardisation in general.

$$ X_{stand} = \frac{X- \mu (X_{train})}{\sigma(X_{train})} $$

*After applying  Standardisation scaling Technique, Feature scaled values lies in between -3 To 3



*Normalization--> We can use Normalization,Only when Feature Follow Normal Distribution. 

$$ X_{Norm} = \frac{X- Min(X_{train})}{Max(X_{train})-Min(X_{train})} $$

*After applying  Normalization scaling Technique, Feature scaled values lies in between 0 To 1


In [16]:
from sklearn.preprocessing import StandardScaler
Sc=StandardScaler()                                    # Here no Need To Provide Any Parameter As Only Mean And Std Required Which Will Calculate by Fit Method, and will perform scaling using Standardisation Formula using Transform Method
X_train[:,3:]= Sc.fit_transform(X_train[:,3:])         # We dont apply scaling on dummy Variable Ex-[0.0, 0.0, 1.0, 38.77777777777778, 52000.0], As Dummy Variable values are already in between -3 to 3
X_test[:,3:]= Sc.transform(X_test[:,3:])               # Same Scaler we have to apply on X_test data, to get Congruent Prediction as we got from training data 

In [17]:
X_train

array([[0.0, 0.0, 1.0, -0.19159184384578545, -1.0781259408412425],
       [0.0, 1.0, 0.0, -0.014117293757057777, -0.07013167641635372],
       [1.0, 0.0, 0.0, 0.566708506533324, 0.633562432710455],
       [0.0, 0.0, 1.0, -0.30453019390224867, -0.30786617274297867],
       [0.0, 0.0, 1.0, -1.9018011447007988, -1.420463615551582],
       [1.0, 0.0, 0.0, 1.1475343068237058, 1.232653363453549],
       [0.0, 1.0, 0.0, 1.4379472069688968, 1.5749910381638885],
       [1.0, 0.0, 0.0, -0.7401495441200351, -0.5646194287757332]],
      dtype=object)

In [18]:
X_test

array([[0.0, 1.0, 0.0, -1.4661817944830124, -0.9069571034860727],
       [1.0, 0.0, 0.0, -0.44973664397484414, 0.2056403393225306]],
      dtype=object)

Congratulations!! Now All Features are on same scale Between -3 to 3, Now we are ready to apply algorithem 