## K-Nearest Neighbors

Steps To Follow:

1.Choose the no of K Neighbors, Default-5

2.Take the K Neasrest Neighbors of New Data According to Euclidene Distance 

3.Among those K Neighbors count the no of data point in Each Category Ex-5 Neighbors are there,3 Neighbors belong to class 0,2 Neighbors Belong to class-1,then our new data will belong to class 0.(As class 0 has maximum voting )

4.To which category maximun voting has done,that will be a pedicted class.

5.For regression Problem Y_pred will be Mean of K Nearest Neighbors 


## Importing the Libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the Dataset

In [2]:
dataset=pd.read_csv(r'C:\Users\Machine Learning\Classification\My Logistic Regression\Social_Network_Ads.csv')
X=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

## Spliting Dataset Into Training And Test 

In [3]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test =train_test_split(X,y,test_size=0.2, random_state=0)

In [4]:
X_test

array([[    35,  27000],
       [    54, 104000],
       [    35,  61000],
       [    32,  18000],
       [    42,  73000],
       [    35,  79000],
       [    46,  79000],
       [    45, 131000],
       [    41,  80000],
       [    31,  15000],
       [    19,  19000],
       [    26,  72000],
       [    33,  69000],
       [    35,  59000],
       [    25,  80000],
       [    27,  57000],
       [    34,  43000],
       [    26,  84000],
       [    60,  34000],
       [    36,  99000],
       [    35,  71000],
       [    22,  55000],
       [    27,  20000],
       [    59,  76000],
       [    41,  51000],
       [    28,  87000],
       [    48,  33000],
       [    47,  30000],
       [    28, 123000],
       [    38,  61000],
       [    19,  70000],
       [    33, 149000],
       [    49,  86000],
       [    40,  57000],
       [    29,  43000],
       [    49,  28000],
       [    22,  81000],
       [    48,  90000],
       [    47,  50000],
       [    26,  16000],


## Feature Scaling

In [5]:
from sklearn.preprocessing import StandardScaler
Sc = StandardScaler()
X_train=Sc.fit_transform(X_train)
X_test = Sc.transform(X_test)

## Training KNN model On Training Data

In [6]:
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2 )
classifier.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

## Predict The New Result

In [7]:
print(classifier.predict(Sc.transform([[30,87000]])))

[0]



## Predicting Test Set Result 

In [8]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))
                 

[[0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]]


## Making the Confusion Matrix

In [9]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)
Score=accuracy_score(y_test,y_pred)
print(Score)

[[49  0]
 [ 4 27]]
0.95
